work_dir: ./work_dir/egogesture/aimclr_finetune_bone

weights: 'work_dir/egogesture/pretext_bone/epoch080_acc33.66_model.pt'
ignore_weights: [encoder_q.fc, encoder_k, queue]

train_feeder: feeder.feeder_egogesture.Feeder
train_feeder_args:
  data_path: /Users/gzp/Desktop/exp/CTR-GCN-main/data/egogesture/train_data.npy
  label_path: /Users/gzp/Desktop/exp/CTR-GCN-main/data/egogesture/train_label.pkl
  split: train
  bone: true  # ✅ 直接使用 bone 数据
  window_size: 50
  random_rot: false
  random_choose: false
  random_move: false
  random_shift: false
  normalization: false
  debug: false
  use_mmap: true

test_feeder: feeder.feeder_egogesture.Feeder
test_feeder_args:
  data_path: /Users/gzp/Desktop/exp/CTR-GCN-main/data/egogesture/val_data.npy
  label_path: /Users/gzp/Desktop/exp/CTR-GCN-main/data/egogesture/val_label.pkl
  split: test
  bone: true  # ✅ 直接使用 bone 数据
  window_size: 50
  normalization: false
  debug: false
  use_mmap: true

model: net.aimclr.AimCLR
model_args:
  base_encoder: net.st_gcn.Model
  pretrain: false
  in_channels: 3
  hidden_channels: 64
  hidden_dim: 256
  num_class: 83
  dropout: 0.5
  graph_args:
    layout: 'egogesture'
    strategy: 'spatial'
  edge_importance_weighting: true

optimizer: SGD
base_lr: 0.01
nesterov: true
weight_decay: 0.0001
step: [50]

device: [0]
batch_size: 32
test_batch_size: 32
num_epoch: 80
stream: joint

save_interval: 5
eval_interval: 5
show_topk: [1, 5]